### PR TITLE
EtcdHealthIndicator should report out-of-service if spring.cloud.etcd.enabled=false

### PR DESCRIPTION
**Pull request by otrosien**
Initial shot (don't know for sure about refreshability of etcdProperties)
there's also no test suite for this project....

### CODE REVIEW

**Comment by spencergibb** [comment]
I'd rather put a conditional on the autoconfig for `spring.cloud.etcd.enabled`.

**Comment by otrosien** [comment]
In other places there is a dedicated property for enabling health checks (e.g. "eureka.client.healthcheck.enabled")
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/eureka/EurekaDiscoveryClientConfiguration.java

**Comment by spencergibb** [comment]
Yup and `@ConditionalOnProperty(value = "eureka.client.enabled", matchIfMissing = true)` on the whole class.

**Comment by otrosien** [comment]
I'll have a look into it, and will open a new PR.

**Pull request closed without merging**
